# Generated by Django 3.1.7 on 2021-03-15 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('ip4', models.CharField(max_length=40, verbose_name='IPv4')),
                ('lab', models.CharField(max_length=100, verbose_name='Laboratory')),
            ],
        ),
    ]
