# Generated by Django 3.1.7 on 2021-03-16 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HiveQueenRest', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clients',
            old_name='ip4',
            new_name='ipv4',
        ),
    ]
