# Generated by Django 3.1.7 on 2021-05-20 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colony', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='id',
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(help_text='it001', max_length=200, primary_key=True, serialize=False),
        ),
    ]
