# Generated by Django 3.1.7 on 2021-05-22 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('colony', '0002_netaddress_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='netaddress',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='colony.client'),
        ),
    ]
